Minigame hole repair
niki4smirn/space-gate pull request #45
Opened 2022-06-07 11:14 UTC by YahorL

2022-06-07 14:32 UTC, DudkoAndrei requested changes

2022-06-07 14:32 UTC, DudkoAndrei commented on Protobuf/minigame_actions.proto
> +  }
может лучше позиция + была ли нажата кнопка?

2022-06-07 14:32 UTC, DudkoAndrei commented on Resources/Images/images.qrc
> +    </qresource>
Зачем каждый раз писать 
```
<qresource>
...
</qresource>
```
?

2022-06-07 14:32 UTC, DudkoAndrei commented on src/Client/Controller/client_controller.cpp
> +  AddEventToSend(event);
По идее, здесь как-то должен использоваться InputController

2022-06-07 14:32 UTC, DudkoAndrei commented on src/Client/Games/HoleRepairMinigameView/hole_repair_view.cpp
> +             - hole.height() / 2);
можно передавать координаты как вещественные числа, и не нужно будет разбираться с разными разрешениями и относительными координатами. Точка (0,0) - верхний левый угол, (1, 1) - нижний правый

2022-06-07 14:32 UTC, DudkoAndrei commented on src/Client/Games/HoleRepairMinigameView/hole_repair_view.cpp
> +             - hole.height() / 2);
можно передавать координаты как вещественные числа, и не нужно будет разбираться с разными разрешениями и относительными координатами. Точка (0,0) - верхний левый угол, (1, 1) - нижний правый

2022-06-07 14:32 UTC, DudkoAndrei commented on src/Client/Games/HoleRepairMinigameView/hole_repair_view.cpp
> +      PaintCursor(&painter);
PaintPlates и PaintTimebar можно вынести

2022-06-07 14:32 UTC, DudkoAndrei commented on src/Client/Games/HoleRepairMinigameView/hole_repair_view.cpp
> +response) {
```
void HoleRepairView::InitializeView(
    const minigame_responses::MinigameResponse& response) {
```

2022-06-07 14:32 UTC, DudkoAndrei commented on src/Client/Games/HoleRepairMinigameView/hole_repair_view.cpp
> +response) {
Аналогично с пред. комментарием

2022-06-07 14:32 UTC, DudkoAndrei commented on CMakeLists.txt
> +            src/Client/InputController/input_names_unix.cpp src/Helpers/Constants/minigames_settings.cpp src/Helpers/Constants/minigames_settings.h)
Почему здесь настройки миниигр?

2022-06-07 14:32 UTC, DudkoAndrei commented on src/Client/Games/HoleRepairMinigameView/hole_repair_view.h
> +};
Может его внутрь класса переместить?

2022-06-07 14:32 UTC, DudkoAndrei commented on src/Helpers/Constants/minigames_settings.cpp
> +constexpr int kAdditionPlates = 0;
За что отвечает этот параметр?

2022-06-07 14:32 UTC, DudkoAndrei commented on src/Server/Games/HoleRepairMinigame/hole_repair.cpp
> +    AbstractMinigame(players, 1000, kGameDuration) {
Откуда 1000?

2022-06-07 14:32 UTC, DudkoAndrei commented on src/Server/Games/HoleRepairMinigame/hole_repair.cpp
> +void HoleRepair::SendResponseMessages() {}
Почему методы не используются?

2022-06-07 14:33 UTC, DudkoAndrei commented
+ Нет смысла в картинке кусроса размера 948x980

2022-06-07 14:35 UTC, DudkoAndrei reviewed
Нет смысла в картинке для курсора разрешение которой почти совпадает с экраном

2022-06-07 15:54 UTC, YahorL commented on src/Client/Controller/client_controller.cpp
> +  AddEventToSend(event);
ну поидее да, но я хотел еще обсудить как будем использовать инпут контроллер

2022-06-07 15:56 UTC, YahorL commented on src/Client/Games/HoleRepairMinigameView/hole_repair_view.cpp
> +      PaintCursor(&painter);
тогда другой порядок прорисовки будет. Например если вынести plates в начало, то получится что дырки будут поверх plates рисоваться

2022-06-07 15:56 UTC, YahorL commented on CMakeLists.txt
> +            src/Client/InputController/input_names_unix.cpp src/Helpers/Constants/minigames_settings.cpp src/Helpers/Constants/minigames_settings.h)
А, ну силайн дэбил и почему то туда все запихивает

2022-06-07 15:57 UTC, YahorL commented on src/Helpers/Constants/minigames_settings.cpp
> +constexpr int kAdditionPlates = 0;
дополнительные плейты
Например если у тебя 10 дырок, то плейтов у тебя может быть больше чтобы было право на ошибку

2022-06-07 15:58 UTC, YahorL commented on src/Server/Games/HoleRepairMinigame/hole_repair.cpp
> +    AbstractMinigame(players, 1000, kGameDuration) {
ну вот так вот

2022-06-07 15:58 UTC, YahorL commented on src/Server/Games/HoleRepairMinigame/hole_repair.cpp
> +void HoleRepair::SendResponseMessages() {}
потому что нахрен не нужны, а реализовать надо

2022-06-07 16:18 UTC, DudkoAndrei commented on src/Helpers/Constants/minigames_settings.cpp
> +constexpr int kAdditionPlates = 0;
Переименуй на kAdditionalPlates

2022-06-07 16:19 UTC, DudkoAndrei commented on src/Client/Games/HoleRepairMinigameView/hole_repair_view.cpp
> +      PaintCursor(&painter);
Можно не только в начало выносить)

2022-06-07 16:21 UTC, DudkoAndrei commented on src/Server/Games/HoleRepairMinigame/hole_repair.cpp
> +void HoleRepair::SendResponseMessages() {}
Можно перенести логику из SendTimeMessage в эти методы

2022-06-07 16:22 UTC, DudkoAndrei commented on CMakeLists.txt
> +            src/Client/InputController/input_names_unix.cpp src/Helpers/Constants/minigames_settings.cpp src/Helpers/Constants/minigames_settings.h)
Когда создаёшь файлы для нового класса Clion даёт выбрать, куда в СMakeLists добавить эти файлы

2022-06-07 16:22 UTC, DudkoAndrei commented on CMakeLists.txt
> +            src/Client/InputController/input_names_unix.cpp src/Helpers/Constants/minigames_settings.cpp src/Helpers/Constants/minigames_settings.h)
Когда создаёшь файлы для нового класса Clion даёт выбрать, куда в СMakeLists добавить эти файлы

2022-06-07 17:03 UTC, YahorL commented on src/Client/Games/HoleRepairMinigameView/hole_repair_view.cpp
> +      PaintCursor(&painter);
всм, несколько свитчей сделать? А какая разница будет, сложнее помоему только станет

2022-06-07 18:00 UTC, DudkoAndrei commented on src/Client/Games/HoleRepairMinigameView/hole_repair_view.cpp
> +      PaintCursor(&painter);
можно что-то и после этих 2-ух свичей написать

2022-06-09 05:52 UTC, DudkoAndrei commented on src/Server/Games/HoleRepairMinigame/hole_repair.cpp
> +}
SendTimeMessage и SendResponseMessages ничем не отличаются, оставь один

2022-06-09 07:39 UTC, niki4smirn submitted a review, later dismissed
![messi](https://user-images.githubusercontent.com/66160046/172791868-3592584f-783b-4424-a1b6-e5fc02ef1dc6.jpg)

2022-06-09 16:45 UTC, merged